<%@ Page Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="GridView.aspx.cs" Inherits="RegistrationPage.GridView" %>
<asp:Content ID="Content1" runat="server" ContentPlaceHolderID="head"></asp:Content>
<asp:Content ID="Content2" runat="server" ContentPlaceHolderID="ContentPlaceHolder">

    <div>
    <table align="right">
        <tr>
            <td>
                <asp:GridView ID="gdView" runat="server" AutoGenerateColumns="False"   
                    BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px"   
                    CellPadding="3" DataKeyNames="id" AutoGenerateDeleteButton="True"   
                    AutoGenerateEditButton="True" onrowcancelingedit="GridViewRowCancelingEdit"   
                    onrowdeleting="GridViewRowDeleting" onrowediting="GridViewRowEditing"   
                    onrowupdating="GridViewRowUpdating" CellSpacing="2">  
                    <Columns> 
                        <asp:TemplateField HeaderText="TrainNo">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtNo" runat="server" Text='<%# Bind("TrainNo") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lblNo" runat="server" Text='<%# Bind("TrainNo") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 
                        <asp:TemplateField HeaderText="TrainName">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtName" runat="server" Text='<%# Bind("TrainName") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lblName" runat="server" Text='<%# Bind("TrainName") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>                         
                        <asp:TemplateField HeaderText="DepartureTime">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtDepartTime" runat="server" Text='<%# Bind("DepartureTime") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lblDepartTime" runat="server" Text='<%# Bind("DepartTime") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 
                        <asp:TemplateField HeaderText="ArrivalTime">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtArrivalTime" runat="server" Text='<%# Bind("ArrivalTime") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lblArrivalTime" runat="server" Text='<%# Bind("ArrivalTime") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 
                        <asp:TemplateField HeaderText="TrainkM">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtKM" runat="server" Text='<%# Bind("TrainKM") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lblKM" runat="server" Text='<%# Bind("TrainKM") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 
                        </Columns>
                        </asp:GridView>
            </td>
        </tr>
    </table>
    </div>

</asp:Content>